# Generated by Django 6.0.7 on 2026-07-19 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('task_sumary', models.CharField(max_length=100)),
                ('task_deatil', models.CharField(max_length=250)),
                ('task_dadline', models.DateTimeField()),
                ('task_status', models.CharField(choices=[('PENDING', 'pending'), ('COMPLETED', 'completed'), ('UNCOMPLETE', 'uncomplete')], max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Task', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
