# Generated by Django 6.0.7 on 2026-07-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_alter_task_created_at_alter_task_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_deatil',
            field=models.TextField(max_length=250),
        ),
    ]
