# Generated by Django 6.0.7 on 2026-07-20 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0007_alter_task_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('COMPLETED', 'completed'), ('UNCOMPLETE', 'uncomplete')], default='pending', max_length=200),
        ),
    ]
